apiVersion: v1
kind: ConfigMap
metadata:
  name: vol-config
data:
  APP_KEY: config-message
  APP_VALUE: Hello there!
---
apiVersion: v1
kind: Pod
metadata:
  name: vol-demo-pod
  labels:
    app: backend
spec:
  containers:
    - image: ubuntu
      name: vol-demo-container
      command:
        [
          "/bin/sh",
          "-c",
          "ls /etc/config/ && cat /etc/config/APP_KEY; echo; cat /etc/config/APP_VALUE; echo",
        ]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: vol-config
# kubectl logs vol-demo-pod
# configMap's data>keys have become the files and the values have become the content of these files

