apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  APP_KEY: config-message
  APP_VALUE: Hello there!
---
apiVersion: v1
kind: Pod
metadata:
  name: env-demo-pod
  labels:
    app: backend
spec:
  containers:
    - image: vivekanandpv/sb-env-app
      name: env-app-container
      env:
        - name: APP_KEY
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: APP_KEY
        - name: APP_VALUE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: APP_VALUE
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
# port-forward 8080
# path in browser: http://localhost:<forward-port>/api/v1/sample
