apiVersion: v1
kind: Pod
metadata:
  name: my-backend-pod
spec:
  containers:
   - image: vivekanandpv/sg-sb-demo
     name: my-backend
     ports:
      - containerPort: 8080
        name: http
        protocol: TCP