apiVersion: v1
kind: Pod
metadata:
  name: mc-pod
  labels:
    app: ng
    version: v1
spec:
  containers:
    - image: nginx
      name: my-nginx-container
      ports:
        - containerPort: 80
          name: http-frontend
          protocol: TCP

    - image: vivekanandpv/sb-api-app
      name: sb-container
      ports:
        - containerPort: 8080
          name: http-backend
          protocol: TCP
