apiVersion: v1
kind: Pod
metadata:
  # In a standalone pod like this, Kubernetes will not generate a name automatically like it does
  # for Deployments. Name is required, without which standalone pod creation fails.
  name: my-nginx-pod
  labels:
    app: ng
    version: v1
spec:
  containers:
    - image: nginx
      name: my-nginx-container
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
