apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-frontend-pod
    spec:
      containers:
      - image: nginx
        name: my-nginx
        ports:
          - containerPort: 80
            name: http
            protocol: TCP