apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
   app: frontend
   version: "1.2.4"
  name: my-app-rs
spec:
  replicas: 3
  selector:
   matchLabels:
    app: my-frontend-pod
  template:
    metadata:
      labels:
        app: my-frontend-pod
    spec:
      containers:
      - image: nginx
        name: my-nginx
        ports:
          - containerPort: 80
            name: http
            protocol: TCP